/*
 * Offline generator: emits the GLSL constant-table block for hevc_cabac.comp
 * directly from the CPU reference tables, so the shader's CABAC tables cannot
 * drift from hevc_tables.h. Not part of the server build.
 *
 * Build/run (from server/encoder/hevc/):
 *   g++ -std=c++20 -I. gpu/gen_cabac_tables.cpp -o /tmp/gen && /tmp/gen > gpu/shaders/cabac_tables.glsl.inc
 */
#include "hevc_tables.h"

#include <cstdio>
#include <vector>

using namespace wivrn::h267::tables;

namespace
{
struct pos
{
	int x, y;
};

// Same up-right diagonal scan as residual_coding.cpp (clause 6.5.3).
std::vector<pos> diag_scan(int size)
{
	std::vector<pos> out;
	int i = 0, x = 0, y = 0;
	bool stop = false;
	while (not stop)
	{
		while (y >= 0)
		{
			if (x < size && y < size)
				out.push_back({x, y});
			--y;
			++x;
		}
		y = x;
		x = 0;
		if ((int)out.size() >= size * size)
			stop = true;
	}
	return out;
}

void emit_scan(const char * name, int size)
{
	auto s = diag_scan(size);
	std::printf("const int %s_x[%zu] = int[%zu](", name, s.size(), s.size());
	for (size_t i = 0; i < s.size(); ++i)
		std::printf("%d%s", s[i].x, i + 1 < s.size() ? ", " : "");
	std::printf(");\n");
	std::printf("const int %s_y[%zu] = int[%zu](", name, s.size(), s.size());
	for (size_t i = 0; i < s.size(); ++i)
		std::printf("%d%s", s[i].y, i + 1 < s.size() ? ", " : "");
	std::printf(");\n");
}
} // namespace

int main()
{
	std::printf("// GENERATED by gen_cabac_tables.cpp from hevc_tables.h -- do not edit.\n\n");

	// Context-block offsets used by the shader.
	std::printf("#define CTX_SPLIT_CODING_UNIT_FLAG %d\n", SPLIT_CODING_UNIT_FLAG);
	std::printf("#define CTX_PART_MODE %d\n", PART_MODE);
	std::printf("#define CTX_PREV_INTRA_LUMA_PRED_FLAG %d\n", PREV_INTRA_LUMA_PRED_FLAG);
	std::printf("#define CTX_INTRA_CHROMA_PRED_MODE %d\n", INTRA_CHROMA_PRED_MODE);
	std::printf("#define CTX_CBF_LUMA %d\n", CBF_LUMA);
	std::printf("#define CTX_CBF_CB_CR %d\n", CBF_CB_CR);
	std::printf("#define CTX_LAST_SIGNIFICANT_COEFF_X_PREFIX %d\n", LAST_SIGNIFICANT_COEFF_X_PREFIX);
	std::printf("#define CTX_LAST_SIGNIFICANT_COEFF_Y_PREFIX %d\n", LAST_SIGNIFICANT_COEFF_Y_PREFIX);
	std::printf("#define CTX_SIGNIFICANT_COEFF_GROUP_FLAG %d\n", SIGNIFICANT_COEFF_GROUP_FLAG);
	std::printf("#define CTX_SIGNIFICANT_COEFF_FLAG %d\n", SIGNIFICANT_COEFF_FLAG);
	std::printf("#define CTX_COEFF_ABS_LEVEL_GREATER1_FLAG %d\n", COEFF_ABS_LEVEL_GREATER1_FLAG);
	std::printf("#define CTX_COEFF_ABS_LEVEL_GREATER2_FLAG %d\n", COEFF_ABS_LEVEL_GREATER2_FLAG);
	std::printf("#define HEVC_CONTEXTS %d\n\n", HEVC_CONTEXTS);

	// init_values for I slices (initType 0) only -- the encoder is all-IDR.
	std::printf("const int init_values0[%d] = int[%d](", HEVC_CONTEXTS, HEVC_CONTEXTS);
	for (int i = 0; i < HEVC_CONTEXTS; ++i)
		std::printf("%d%s", init_values[0][i], i + 1 < HEVC_CONTEXTS ? ", " : "");
	std::printf(");\n\n");

	// rangeTabLps flattened to [64*4].
	std::printf("const int rangeTabLps[256] = int[256](");
	for (int i = 0; i < 64; ++i)
		for (int j = 0; j < 4; ++j)
			std::printf("%d%s", rangeTabLps[i][j], (i * 4 + j) < 255 ? ", " : "");
	std::printf(");\n");

	std::printf("const int transIdxLps[64] = int[64](");
	for (int i = 0; i < 64; ++i)
		std::printf("%d%s", transIdxLps[i], i < 63 ? ", " : "");
	std::printf(");\n");
	std::printf("const int transIdxMps[64] = int[64](");
	for (int i = 0; i < 64; ++i)
		std::printf("%d%s", transIdxMps[i], i < 63 ? ", " : "");
	std::printf(");\n\n");

	// Scan orders.
	emit_scan("scan16", 4); // 4x4 coefficient scan
	emit_scan("scan_sb2", 2); // 2x2 sub-block scan (8x8 TU)
	std::printf("\n");

	// last_significant_coeff group tables (9.3.3.3).
	std::printf("const int group_idx[32] = int[32](0, 1, 2, 3, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9);\n");
	std::printf("const int min_in_group[10] = int[10](0, 1, 2, 3, 4, 6, 8, 12, 16, 24);\n");
	// sig_coeff_flag ctx map for 4x4 (9.3.4.2.5).
	std::printf("const int ctx_idx_map[16] = int[16](0, 1, 4, 5, 2, 3, 4, 5, 6, 6, 8, 8, 7, 7, 8, 8);\n");

	return 0;
}
