/*
 * Offline generator: emits the GLSL constant-table block for h264_cavlc_emit.comp
 * from the same H.264 CAVLC tables as cavlc.cpp, so the shader tables cannot
 * drift. Not part of the server build.
 *
 * Build/run (from server/encoder/h264/):
 *   g++ -std=c++20 gpu/gen_cavlc_tables.cpp -o /tmp/gen264 && /tmp/gen264 > gpu/shaders/cavlc_tables.glsl.inc
 */
#include <cstdint>
#include <cstdio>

// The tables must match cavlc.cpp exactly.
static const uint8_t coeff_token_len[4][4 * 17] = {
        {1, 0, 0, 0, 6, 2, 0, 0, 8, 6, 3, 0, 9, 8, 7, 5, 10, 9, 8, 6, 11, 10, 9, 7, 13, 11, 10, 8, 13, 13, 11, 9, 13, 13, 13, 10, 14, 14, 13, 11, 14, 14, 14, 13, 15, 15, 14, 14, 15, 15, 15, 14, 16, 15, 15, 15, 16, 16, 16, 15, 16, 16, 16, 16, 16, 16, 16, 16},
        {2, 0, 0, 0, 6, 2, 0, 0, 6, 5, 3, 0, 7, 6, 6, 4, 8, 6, 6, 4, 8, 7, 7, 5, 9, 8, 8, 6, 11, 9, 9, 6, 11, 11, 11, 7, 12, 11, 11, 9, 12, 12, 12, 11, 12, 12, 12, 11, 13, 13, 13, 12, 13, 13, 13, 13, 13, 14, 13, 13, 14, 14, 14, 13, 14, 14, 14, 14},
        {4, 0, 0, 0, 6, 4, 0, 0, 6, 5, 4, 0, 6, 5, 5, 4, 7, 5, 5, 4, 7, 5, 5, 4, 7, 6, 6, 4, 7, 6, 6, 4, 8, 7, 7, 5, 8, 8, 7, 6, 9, 8, 8, 7, 9, 9, 8, 8, 9, 9, 9, 8, 10, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10},
        {6, 0, 0, 0, 6, 6, 0, 0, 6, 6, 6, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6}};
static const uint8_t coeff_token_bits[4][4 * 17] = {
        {1, 0, 0, 0, 5, 1, 0, 0, 7, 4, 1, 0, 7, 6, 5, 3, 7, 6, 5, 3, 7, 6, 5, 4, 15, 6, 5, 4, 11, 14, 5, 4, 8, 10, 13, 4, 15, 14, 9, 4, 11, 10, 13, 12, 15, 14, 9, 12, 11, 10, 13, 8, 15, 1, 9, 12, 11, 14, 13, 8, 7, 10, 9, 12, 4, 6, 5, 8},
        {3, 0, 0, 0, 11, 2, 0, 0, 7, 7, 3, 0, 7, 10, 9, 5, 7, 6, 5, 4, 4, 6, 5, 6, 7, 6, 5, 8, 15, 6, 5, 4, 11, 14, 13, 4, 15, 10, 9, 4, 11, 14, 13, 12, 8, 10, 9, 8, 15, 14, 13, 12, 11, 10, 9, 12, 7, 11, 6, 8, 9, 8, 10, 1, 7, 6, 5, 4},
        {15, 0, 0, 0, 15, 14, 0, 0, 11, 15, 13, 0, 8, 12, 14, 12, 15, 10, 11, 11, 11, 8, 9, 10, 9, 14, 13, 9, 8, 10, 9, 8, 15, 14, 13, 13, 11, 14, 10, 12, 15, 10, 13, 12, 11, 14, 9, 12, 8, 10, 13, 8, 13, 7, 9, 12, 9, 12, 11, 10, 5, 8, 7, 6, 1, 4, 3, 2},
        {3, 0, 0, 0, 0, 1, 0, 0, 4, 5, 6, 0, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63}};
static const uint8_t chroma_dc_coeff_token_len[4 * 5] = {2, 0, 0, 0, 6, 1, 0, 0, 6, 6, 3, 0, 6, 7, 7, 6, 6, 8, 8, 7};
static const uint8_t chroma_dc_coeff_token_bits[4 * 5] = {1, 0, 0, 0, 7, 1, 0, 0, 4, 6, 1, 0, 3, 3, 2, 5, 2, 3, 2, 0};
static const uint8_t total_zeros_len[15][16] = {
        {1, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 9}, {3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 6, 6}, {4, 3, 3, 3, 4, 4, 3, 3, 4, 5, 5, 6, 5, 6}, {5, 3, 4, 4, 3, 3, 3, 4, 3, 4, 5, 5, 5}, {4, 4, 4, 3, 3, 3, 3, 3, 4, 5, 4, 5}, {6, 5, 3, 3, 3, 3, 3, 3, 4, 3, 6}, {6, 5, 3, 3, 3, 2, 3, 4, 3, 6}, {6, 4, 5, 3, 2, 2, 3, 3, 6}, {6, 6, 4, 2, 2, 3, 2, 5}, {5, 5, 3, 2, 2, 2, 4}, {4, 4, 3, 3, 1, 3}, {4, 4, 2, 1, 3}, {3, 3, 1, 2}, {2, 2, 1}, {1, 1}};
static const uint8_t total_zeros_bits[15][16] = {
        {1, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 1}, {7, 6, 5, 4, 3, 5, 4, 3, 2, 3, 2, 3, 2, 1, 0}, {5, 7, 6, 5, 4, 3, 4, 3, 2, 3, 2, 1, 1, 0}, {3, 7, 5, 4, 6, 5, 4, 3, 3, 2, 2, 1, 0}, {5, 4, 3, 7, 6, 5, 4, 3, 2, 1, 1, 0}, {1, 1, 7, 6, 5, 4, 3, 2, 1, 1, 0}, {1, 1, 5, 4, 3, 3, 2, 1, 1, 0}, {1, 1, 1, 3, 3, 2, 2, 1, 0}, {1, 0, 1, 3, 2, 1, 1, 1}, {1, 0, 1, 3, 2, 1, 1}, {0, 1, 1, 2, 1, 3}, {0, 1, 1, 1, 1}, {0, 1, 1, 1}, {0, 1, 1}, {0, 1}};
static const uint8_t chroma_dc_total_zeros_len[3][4] = {{1, 2, 3, 3}, {1, 2, 2, 0}, {1, 1, 0, 0}};
static const uint8_t chroma_dc_total_zeros_bits[3][4] = {{1, 1, 1, 0}, {1, 1, 0, 0}, {1, 0, 0, 0}};
static const uint8_t run_len[7][16] = {{1, 1}, {1, 2, 2}, {2, 2, 2, 2}, {2, 2, 2, 3, 3}, {2, 2, 3, 3, 3, 3}, {2, 3, 3, 3, 3, 3, 3}, {3, 3, 3, 3, 3, 3, 3, 4, 5, 6, 7, 8, 9, 10, 11}};
static const uint8_t run_bits[7][16] = {{1, 0}, {1, 1, 0}, {3, 2, 1, 0}, {3, 2, 1, 1, 0}, {3, 2, 3, 2, 1, 0}, {3, 0, 1, 3, 2, 5, 4}, {7, 6, 5, 4, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1}};

template <int R, int C>
void emit2(const char * name, const uint8_t (&t)[R][C], int cols)
{
	printf("const uint %s[%d] = uint[%d](", name, R * cols, R * cols);
	for (int i = 0; i < R; ++i)
		for (int j = 0; j < cols; ++j)
			printf("%du%s", t[i][j], (i * cols + j) < R * cols - 1 ? ", " : "");
	printf(");\n");
}
void emit1(const char * name, const uint8_t * t, int n)
{
	printf("const uint %s[%d] = uint[%d](", name, n, n);
	for (int i = 0; i < n; ++i)
		printf("%du%s", t[i], i < n - 1 ? ", " : "");
	printf(");\n");
}

int main()
{
	printf("// GENERATED by gen_cavlc_tables.cpp -- do not edit.\n\n");
	// coeff_token: flatten [4][68] with 17*4 cols; index nCtab*68 + tc*4 + t1.
	printf("const uint ctk_len[%d] = uint[%d](", 4 * 68, 4 * 68);
	for (int a = 0; a < 4; ++a) for (int i = 0; i < 68; ++i) printf("%du%s", coeff_token_len[a][i], (a * 68 + i) < 4 * 68 - 1 ? ", " : "");
	printf(");\n");
	printf("const uint ctk_bits[%d] = uint[%d](", 4 * 68, 4 * 68);
	for (int a = 0; a < 4; ++a) for (int i = 0; i < 68; ++i) printf("%du%s", coeff_token_bits[a][i], (a * 68 + i) < 4 * 68 - 1 ? ", " : "");
	printf(");\n");
	emit1("cdc_ctk_len", chroma_dc_coeff_token_len, 20);
	emit1("cdc_ctk_bits", chroma_dc_coeff_token_bits, 20);
	// total_zeros [15][16] flat
	printf("const uint tz_len[%d] = uint[%d](", 15 * 16, 15 * 16);
	for (int i = 0; i < 15; ++i) for (int j = 0; j < 16; ++j) printf("%du%s", total_zeros_len[i][j], (i * 16 + j) < 15 * 16 - 1 ? ", " : "");
	printf(");\n");
	printf("const uint tz_bits[%d] = uint[%d](", 15 * 16, 15 * 16);
	for (int i = 0; i < 15; ++i) for (int j = 0; j < 16; ++j) printf("%du%s", total_zeros_bits[i][j], (i * 16 + j) < 15 * 16 - 1 ? ", " : "");
	printf(");\n");
	emit2("cdc_tz_len", chroma_dc_total_zeros_len, 4);
	emit2("cdc_tz_bits", chroma_dc_total_zeros_bits, 4);
	printf("const uint run_len[%d] = uint[%d](", 7 * 16, 7 * 16);
	for (int i = 0; i < 7; ++i) for (int j = 0; j < 16; ++j) printf("%du%s", run_len[i][j], (i * 16 + j) < 7 * 16 - 1 ? ", " : "");
	printf(");\n");
	printf("const uint run_bits[%d] = uint[%d](", 7 * 16, 7 * 16);
	for (int i = 0; i < 7; ++i) for (int j = 0; j < 16; ++j) printf("%du%s", run_bits[i][j], (i * 16 + j) < 7 * 16 - 1 ? ", " : "");
	printf(");\n");
	printf("const uint zigzag4[16] = uint[16](0u,1u,4u,8u,5u,2u,3u,6u,9u,12u,13u,10u,7u,11u,14u,15u);\n");
	return 0;
}
